version: '2'
services:
  db:
    image: postgres:9.4
    container_name: db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      # - ./config/pg_hba.conf:/var/lib/postgresql/data/pgdata/pg_hba.conf
    ports:
      - "5432:5432"
  odoo:
    image: odoo
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
  # odoo_web_server:
  #   image: nginx
  #   container_name: odoo_web_server
  #   depends_on:
  #     - odoo
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - '80:80'
  #   links:
  #     - odoo:odoo
volumes:
  odoo-web-data:
    # external: true
  odoo-db-data:
    # external: true